### ISSUE TITLE
Configuration inside package.json

### ISSUE THREAD

**Issue by niksy** [bodokaiser/node-shortify#4]
Is it possible to define configuration inside package.json?

Something like:

```json
{
  "browserify": {
    "transform": ["shortify"]
  },
  "shortify": {
    "app/core": "./lib/core"
  }
}
```

**Comment by bodokaiser** [comment]
You can easily write your [own loader](https://github.com/satisfeet/jacana/blob/master/lib/config/index.js).

Beside this I do not think it is semantically correct to mix application configuration with dependency management. Think of two extreme cases: One where you have a lot of configuration and one where you have a lot of dependencies and npm like package meta data.
