### ISSUE TITLE
npm version > 2.11.*

### ISSUE THREAD

**Issue by gpaton** [bodokaiser/node-shortify#5]
Hello,

This packages requires npm in its `2.11.*` version, while the latest version is today `2.12.7`.
```
shortify@0.0.4: wanted: {"node":"0.12.x","npm":"2.11.x"} (current: {"node":"0.12.7","npm":"2.12.1"})
```
Is it compatible ? If so, would you please upgrade requirement in `package.json` ?

**Comment by bodokaiser** [comment]
Hello,

Could you send a PR?

Thank you

**Comment by gpaton** [comment]
PR https://github.com/bodokaiser/node-shortify/pull/6 sent

**Comment by gpaton** [comment]
Fixed by merged PR https://github.com/bodokaiser/node-shortify/pull/6
