### ISSUE TITLE
Unexpected alias for files

### ISSUE THREAD

**Issue by frankcortes** [bodokaiser/node-shortify#7]
With this configuration:
```
shortify({
    'myModule': 'modules'
})
```
I'm using this require:
`require 'myModule_view'`

Shortify transforms this code into `require 'modules/_view'`, which is not the expected result (it should be `require 'myModule_view'` *directly*)

**Comment by bodokaiser** [comment]
Could you provide a test case? Maybe this is a coffee script problem.

**Comment by alex-pex** [comment]
Same problem here. It seems alias is used as a basic text replacement.

eg:
```
shortify({
    'App': '__toto__'
})
```

with `require('App/AppModules/view.js')`
will be replaced by : `require('__toto__/__toto__Modules/view.js');`

require strings should be split using `/` delimiter, then if an exact match is found within string parts it should replace it. With this behavior
`require('App/AppModules/view.js')`
may be replaced by : `require('__toto__/AppModules/view.js');` which is a more predictible behavior

**Comment by bodokaiser** [comment]
I agree. Would you send a PR?

**Comment by alex-pex** [comment]
Done!
